modified files, testing for FeatureBuilder
se-sic/vara-feature pull request #102
Opened 2022-12-15 13:19 UTC by sarvech76

2023-03-06 14:46 UTC, sarvech76 commented
-cleaned the repository
-updated featureModelBuilder python bindings

2023-03-09 08:29 UTC, vulder requested changes

2023-03-09 08:29 UTC, vulder commented on bindings/python/vara-feature/pybind_FeatureModelBuilder.cpp
> +#include <bits/stdc++.h>
```suggestion
#include "vara/Feature/FeatureModel.h"
#include "vara/Feature/FeatureModelBuilder.h"
#include "vara/Feature/FeatureModelTransaction.h"

#include "pybind11/pybind11.h"
#include "pybind11/stl.h"
#include "pybind_common.h"

#include <filesystem>
#include <memory>
```

2023-03-09 08:29 UTC, vulder commented on bindings/python/vara-feature/pybind_FeatureModelBuilder.cpp
> +        );
```suggestion
        .def(
            "build_feature_model",
            [](vf::FeatureModelBuilder &FMB){
                return FMB.buildFeatureModel();
            }
        );
```

2023-03-09 08:29 UTC, vulder commented on bindings/python/vara-feature/pybind_FeatureModelBuilder.cpp
> +        )
```suggestion
        .def(
            "make_binary_feature",
            [](vf::FeatureModelBuilder &FMB, std::string feature_name, bool Opt){
                return FMB.makeFeature<vf::BinaryFeature>(feature_name); 
            }
        )
```

Please don't add any trailing whitespaces.

2023-03-09 08:29 UTC, vulder commented on bindings/python/vara-feature/pybind_FeatureModelBuilder.cpp
> +        )
```suggestion
        .def(
            "add_an_edge",
            [](vf::FeatureModelBuilder &FMB, std::string parent_name, std::string feature_name){
                return FMB.addEdge(parent_name, feature_name);
            }
        )
```

2023-03-09 08:29 UTC, vulder commented on bindings/python/vara-feature/pybind_FeatureModelBuilder.cpp
> +        )
```suggestion
        .def(
            "emplace_relationship",
            [](vf::FeatureModelBuilder &FMB, std::string parent_name, std::string relation) {
 
                vf::Relationship::RelationshipKind RK;
                if (relation == "OR"){
                    RK = vf::Relationship::RelationshipKind::RK_OR;
                }
                else if (relation == "XOR"){
                    RK = vf::Relationship::RelationshipKind::RK_ALTERNATIVE;
                }

                return FMB.emplaceRelationship(RK, parent_name);
            }
        )
```

2023-03-09 08:29 UTC, vulder commented on bindings/python/vara-feature/pybind_FeatureModelBuilder.cpp
> +        )
```suggestion
        .def(
            "add_boolean_constraint",
            [](vf::FeatureModelBuilder &FMB, vf::Constraint &C){
                return FMB.addConstraint(std::make_unique<vf::FeatureModel::BooleanConstraint> (C.clone()) );
            }
        )
```

2023-03-09 08:29 UTC, vulder commented on bindings/python/vara-feature/pybind_FeatureModelBuilder.cpp
> +        )
```suggestion
        .def(
            "add_non_boolean_constraint",
            [](vf::FeatureModelBuilder &FMB, vf::Constraint &C){
                return FMB.addConstraint(std::make_unique<vf::FeatureModel::NonBooleanConstraint> (C.clone()) );
            }
        )
```

2023-03-09 08:29 UTC, vulder commented on bindings/python/vara-feature/pybind_FeatureModelBuilder.cpp
> +        )
```suggestion
        .def(
            "set_vm_name",
            [](vf::FeatureModelBuilder &FMB, std::string name){
                return FMB.setVmName(name);
            }
        )
```

2023-03-09 08:29 UTC, vulder commented on bindings/python/vara-feature/pybind_FeatureModelBuilder.cpp
> +        )
```suggestion
        .def(
            "set_path",
            [](vf::FeatureModelBuilder &FMB, fs::path path){
                return FMB.setPath(path);
            }
        )
```

2023-03-09 08:29 UTC, vulder commented on bindings/python/vara-feature/pybind_FeatureModelBuilder.cpp
> +        )
```suggestion
        .def(
            "set_commit",
            [](vf::FeatureModelBuilder &FMB, fs::path commit){
                return FMB.setCommit(commit);
            }
        )
```

2023-03-09 08:29 UTC, vulder commented on bindings/python/vara-feature/pybind_FeatureModelBuilder.cpp
> +        )
```suggestion
        .def(
            "make_root",
            [](vf::FeatureModelBuilder &FMB, std::string name){
                return FMB.makeRoot(name);
            }
        )
```

2023-03-09 08:29 UTC, vulder commented on bindings/python/vara-feature/pybind_FeatureModelBuilder.cpp
> +        )
Also, please add a bit of documentation to the bindings.
For example:
```
        .def(
            "make_binary_feature",
            [](vf::FeatureModelBuilder &FMB, std::string feature_name, bool Opt){
                return FMB.makeFeature<vf::BinaryFeature>(feature_name); 
            },
            R"pbdoc(Create a new binary `Feature` with the given `feature_name`.)pbdoc"
        )
```

2023-03-10 12:46 UTC, vulder approved these changes

2023-03-10 12:46 UTC, merged