Integrate CSV parser to parse sample sets
se-sic/vara-feature pull request #105
Opened 2022-12-19 14:06 UTC by ChristianKaltenecker

2023-01-17 21:17 UTC, vulder requested changes
Rest looks good.

Just one thing, I might have missed it. Where is the writing of the other config format for the TS? Or should we add it afterwards?

2023-01-17 21:17 UTC, vulder commented on include/vara/Sampling/SampleSetParser.h
> +  /// \param csv the path to the csv file as a string
```suggestion
  ///
  /// \param Model the corresponding feature model
  /// \param csv the path to the csv file as a string
  ///
```

2023-01-17 21:17 UTC, vulder commented on lib/Sampling/SampleSetParser.cpp
> +            F->getKind() == feature::Feature::FeatureKind::FK_ROOT) {
```suggestion
        if (auto Kind = F->getKind(); Kind == feature::Feature::FeatureKind::FK_BINARY ||
            Kind == feature::Feature::FeatureKind::FK_ROOT) {
```

2023-01-17 21:17 UTC, vulder commented on unittests/Sampling/SampleSetParserTests.cpp
> +  EXPECT_EQ(Configs->size(), 40);
```suggestion
  ASSERT_EQ(Configs->size(), 40);
```

2023-01-17 21:17 UTC, vulder commented on unittests/Sampling/SampleSetParserTests.cpp
> +  // Check the configuration options of the last configuration
```suggestion
  testConfigurationOption(FirstConfig, "cells", "55");
  
  // Check the configuration options of the last configuration
```

2023-01-17 21:17 UTC, vulder commented on unittests/Sampling/SampleSetParserTests.cpp
> +  // Check the configuration options of the first configuration
```suggestion

  // Check the configuration options of the first configuration
```

2023-01-19 09:14 UTC, vulder approved these changes

2023-01-19 12:45 UTC, s9latimm approved these changes

2023-01-19 15:28 UTC, merged