Add python bindings for configurations
se-sic/vara-feature pull request #125
Opened 2023-09-15 11:49 UTC by danjujan

2023-09-15 13:52 UTC, vulder requested changes
Except for the comment below, LGTM

2023-09-15 13:52 UTC, vulder commented on setup.py
> +            cmake_args.append('-DVARA_FEATURE_BUILD_Z3_SOLVER=False')
I'm not sure if this is a good way to determine if we should build the solver.
1) the path is a system specific
2) we might want to build the solver from scratch even for those system, as we depend on a very specific version of z3. (The debian 11 can cause problems)

Maybe we should keep building the solver as the default and give the user a option to disable that? Or, if it works for you, only you use the local one.

2025-03-03 16:40 UTC, boehmseb requested changes

2025-03-03 16:40 UTC, boehmseb commented on include/vara/Solver/Solver.h
> +  virtual Result<SolverErrorCode, uint64_t> getNumberValidConfigurations() = 0;
This part was removed by 864ff022ee and should stay removed.
The problem here is that these functions modify solver state in a way that interferes with the result of other solver functions.

I think this PR merged an older version of the branch that eventually was merged as 864ff022ee and therefore contains some outdated code. I try to mark all the relevant locations, but as far as I can see, all changes to the solver code in this PR should be reverted.

```suggestion
```

2025-03-03 16:40 UTC, boehmseb commented on include/vara/Solver/Z3Solver.h
> +
```suggestion
```

2025-03-03 16:40 UTC, boehmseb commented on include/vara/Solver/Z3Solver.h
> +  bool Dirty = false;
```suggestion
```

2025-03-03 16:40 UTC, boehmseb commented on lib/Solver/Z3Solver.cpp
> +
```suggestion
```

2025-03-03 16:40 UTC, boehmseb commented on lib/Solver/Z3Solver.cpp
> -  excludeCurrentConfiguration();
Need to be reinstated.

2025-03-03 16:40 UTC, boehmseb commented on lib/Solver/Z3Solver.cpp
> +
```suggestion
```

2025-03-03 18:24 UTC, vulder approved these changes

2025-03-03 18:48 UTC, boehmseb approved these changes

2025-03-03 18:49 UTC, merged