Fixes for last xml extension
se-sic/vara-feature pull request #42
Opened 2021-02-22 10:10 UTC by padupr

Completes #27 

- commit getter
- Location constructor with default category
- tests for python bindings

2021-02-22 10:12 UTC, padupr commented
There should be a setter for the commit value, should this be a transaction?

2021-02-23 12:40 UTC, vulder approved these changes

2021-02-23 18:39 UTC, vulder requested changes

2021-02-23 18:39 UTC, vulder commented on include/vara/Feature/FeatureModel.h
> +  void setCommit(llvm::StringRef Str) { Commit = Str; }
```suggestion
  void setCommit(std::string Str) { Commit = std::move(Str); }
```

2021-02-23 18:39 UTC, vulder commented on bindings/python/vara-feature/pybind_FeatureModel.cpp
> +          [](vf::FeatureModel &FM, std::string &Commit) {
Use as string value and move it or a `const &` but value should work better here.

2021-02-26 12:01 UTC, vulder approved these changes

2021-02-26 12:03 UTC, merged