Added MemberOffset to XML Parser
se-sic/vara-feature pull request #69
Opened 2021-10-29 10:53 UTC by Zatho

Defined XMLConstant MemberOffset in SourceRange
Extended FeatureModelParser to extract MemberOffset as std::string
Extended FeatureSourceRange with std::string MemberOffset

Need feedback particularly on:
- the type conversion xmlChar* to std::string.
- the use of std::string for the MemberOffset, is that what we want?

related se-sic/VaRA#823

2021-12-02 09:39 UTC, vulder requested changes
We should add a few tests that cover the new member offset feature.

2021-12-02 09:39 UTC, vulder commented on include/vara/Feature/FeatureSourceRange.h
> +                     std::string MemberOffset = "")
Why do we need two different `MemberOffset` defaults? Having `nullopt` and `""`. Would it not be better to have the same behavior independent on which ctor is called?

2021-12-02 09:39 UTC, vulder commented on unittests/Feature/FeatureSourceRange.cpp
> +  auto FSR = std::make_unique<FeatureSourceRange>(FeatureSourceRange(
Why do we need a direct ctor call here? This would then copy construct the FSR in the unique_ptr with the constructed FSR.

2021-12-15 12:22 UTC, vulder reviewed
Overall, the current state looks fine to me.


@s9latimm Should be add a specific class to represent that MemberOffset?
Could be helpful, as it makes accessing the data easier, e.g.:
```
class FeatureMemberOffset {
  llvm::StringRef className() const;
  llvm::StringRef memberName() const;
};
```

+ Do you think we want/need nesting? I guess, the most common case will be without nesting, so just implementing `Class::Member` should be enough.

2021-12-15 12:22 UTC, vulder commented on include/vara/Feature/FeatureSourceRange.h
> +      StrS << " MemberOffset: " << &MemberOffset.value();
Why is it necessary here to take the address of `MemberOffset`? Should value not just return a string?

2021-12-15 19:33 UTC, s9latimm commented
LGTM

> Overall, the current state looks fine to me.
> 
> @s9latimm Should be add a specific class to represent that MemberOffset? Could be helpful, as it makes accessing the data easier, e.g.:
> 
> ```
> class FeatureMemberOffset {
>   llvm::StringRef className() const;
>   llvm::StringRef memberName() const;
> };
> ```
> 
>     * Do you think we want/need nesting? I guess, the most common case will be without nesting, so just implementing `Class::Member` should be enough.

Having this information allow us to easily dump the offset and probably makes  processing / compiling with a FM easier, but I am not sure yet, if we really need this though.

On the other hand I think we are currently fine without fully supporting nested members.

2021-12-15 19:34 UTC, s9latimm approved these changes

2022-01-13 09:35 UTC, vulder approved these changes

2022-01-13 09:35 UTC, vulder commented on include/vara/Feature/FeatureSourceRange.h
> +    virtual ~FeatureMemberOffset() = default;
```suggestion
```
We only need to provide the special member functions, in case we change one.

2022-01-13 12:59 UTC, merged